/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.iua.presentation;

/**
 *
 * @author Giuliano
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Socio = new javax.swing.JMenu();
        cargarS = new javax.swing.JMenuItem();
        modificarS = new javax.swing.JMenuItem();
        eliminarSocio = new javax.swing.JMenuItem();
        buscarSocio = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cargarReserva = new javax.swing.JMenuItem();
        modificarReserva = new javax.swing.JMenuItem();
        eliminarReserva = new javax.swing.JMenuItem();
        buscarReserva = new javax.swing.JMenuItem();
        mostrarReservas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Club");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 495));
        setResizable(false);

        escritorio.setBackground(new java.awt.Color(153, 153, 153));
        escritorio.setForeground(new java.awt.Color(144, 82, 82));
        escritorio.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                escritorioAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(254, 254, 254));

        Socio.setBackground(new java.awt.Color(254, 254, 254));
        Socio.setForeground(new java.awt.Color(1, 1, 1));
        Socio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/socioM.jpg"))); // NOI18N
        Socio.setText("Socio");
        Socio.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        cargarS.setText("Cargar ");
        cargarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarSActionPerformed(evt);
            }
        });
        Socio.add(cargarS);

        modificarS.setText("Modificar");
        modificarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarSActionPerformed(evt);
            }
        });
        Socio.add(modificarS);

        eliminarSocio.setText("Eliminar");
        eliminarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarSocioActionPerformed(evt);
            }
        });
        Socio.add(eliminarSocio);

        buscarSocio.setText("Buscar");
        buscarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarSocioActionPerformed(evt);
            }
        });
        Socio.add(buscarSocio);

        jMenuItem6.setText("Mostrar");
        Socio.add(jMenuItem6);

        jMenuBar1.add(Socio);

        jMenu2.setBackground(new java.awt.Color(254, 254, 254));
        jMenu2.setForeground(new java.awt.Color(1, 1, 1));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reservaM.jpg"))); // NOI18N
        jMenu2.setText("Reserva");
        jMenu2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        cargarReserva.setText("Cargar");
        cargarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarReservaActionPerformed(evt);
            }
        });
        jMenu2.add(cargarReserva);

        modificarReserva.setText("Modificar");
        modificarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarReservaActionPerformed(evt);
            }
        });
        jMenu2.add(modificarReserva);

        eliminarReserva.setText("Eliminar");
        eliminarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarReservaActionPerformed(evt);
            }
        });
        jMenu2.add(eliminarReserva);

        buscarReserva.setText("Buscar");
        buscarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarReservaActionPerformed(evt);
            }
        });
        jMenu2.add(buscarReserva);

        mostrarReservas.setText("Mostrar");
        jMenu2.add(mostrarReservas);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(1, 1, 1));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pagoM.jpg"))); // NOI18N
        jMenu3.setText("Pago");
        jMenu3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jMenuItem1.setText("Cargar");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Modificar");
        jMenu3.add(jMenuItem2);

        jMenuItem4.setText("Eliminar");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Buscar");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(1, 1, 1));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioM.jpg"))); // NOI18N
        jMenu4.setText("Usuario");
        jMenu4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu5.setForeground(new java.awt.Color(1, 1, 1));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ubicacionM.jpg"))); // NOI18N
        jMenu5.setText("Barrio");
        jMenu5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jMenuItem7.setText("Modificar");
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("Eliminar");
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        jMenu6.setForeground(new java.awt.Color(1, 1, 1));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actividadM.jpg"))); // NOI18N
        jMenu6.setText("Actividad");
        jMenu6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jMenuItem9.setText("Mostrar");
        jMenu6.add(jMenuItem9);

        jMenuBar1.add(jMenu6);

        jMenu7.setForeground(new java.awt.Color(1, 1, 1));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salirM.jpg"))); // NOI18N
        jMenu7.setText("Salir");
        jMenu7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cargarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarSActionPerformed
        // TODO add your handling code here: 
        cargarSocio cs = new cargarSocio();
        escritorio.add(cs);
        cs.show();
    }//GEN-LAST:event_cargarSActionPerformed

    private void modificarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarSActionPerformed
        // TODO add your handling code here:
        modificarSocio ms = new modificarSocio();
        escritorio.add(ms);
        ms.show();
    }//GEN-LAST:event_modificarSActionPerformed

    private void eliminarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarSocioActionPerformed
        // TODO add your handling code here:
        eliminarSocio es = new eliminarSocio();
        escritorio.add(es);
        es.show();
    }//GEN-LAST:event_eliminarSocioActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenu7MouseClicked

    private void buscarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarSocioActionPerformed
        // TODO add your handling code here:
        buscarSocio bs = new buscarSocio();
        escritorio.add(bs);
        bs.show();
    }//GEN-LAST:event_buscarSocioActionPerformed

    private void escritorioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_escritorioAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_escritorioAncestorAdded

    private void cargarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarReservaActionPerformed
        // TODO add your handling code here:
        cargarReserva cr = new cargarReserva();
        escritorio.add(cr);
        cr.show();
    }//GEN-LAST:event_cargarReservaActionPerformed

    private void modificarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarReservaActionPerformed
        // TODO add your handling code here:
        modificarReserva mr = new modificarReserva();
        escritorio.add(mr);
        mr.show();
    }//GEN-LAST:event_modificarReservaActionPerformed

    private void eliminarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarReservaActionPerformed
        // TODO add your handling code here:
        eliminarReserva er = new eliminarReserva();
        escritorio.add(er);
        er.show();
    }//GEN-LAST:event_eliminarReservaActionPerformed

    private void buscarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarReservaActionPerformed
        // TODO add your handling code here:
        buscarReserva bs = new buscarReserva();
        escritorio.add(bs);
        bs.show();
    }//GEN-LAST:event_buscarReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Socio;
    private javax.swing.JMenuItem buscarReserva;
    private javax.swing.JMenuItem buscarSocio;
    private javax.swing.JMenuItem cargarReserva;
    private javax.swing.JMenuItem cargarS;
    private javax.swing.JMenuItem eliminarReserva;
    private javax.swing.JMenuItem eliminarSocio;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem modificarReserva;
    private javax.swing.JMenuItem modificarS;
    private javax.swing.JMenuItem mostrarReservas;
    // End of variables declaration//GEN-END:variables
}
